RG351V Theme Updates Part 1
351ELEC/351ELEC pull request #335
Opened 2021-05-01 15:20 UTC by szalik-rg351

So here is basicly some starter pack update for rg351V im gonna drop more soon

2021-05-01 15:43 UTC, szalik-rg351 commented
the metadata update for "Remove ._ files" need to be tested, i copy paste it and replace infromation, so there should not be a problem

2021-05-01 21:33 UTC, Cebion approved these changes
Great Job Szalik

2021-05-01 21:34 UTC, Cebion approved these changes
No Objections

2021-05-01 21:35 UTC, Cebion approved these changes
No Objections

2021-05-01 21:39 UTC, Cebion reviewed
Needs to be tested in build

2021-05-01 21:40 UTC, Cebion approved these changes
Approved

2021-05-02 02:14 UTC, anthonycaccese requested changes

2021-05-02 02:14 UTC, anthonycaccese commented on metadata/RG351P/themes.cfg
> +Handheld-Simple-NOT-SUPPORTED https://github.com/Rican7/es-theme-handheld-simple
Please change this to just Handheld-Simple.   The theme works well for a set of core systems was one of the first ones that we made for 351ELEC.   Not supported implies that the theme doesn't work at all.

2021-05-02 02:14 UTC, anthonycaccese commented on metadata/RG351V/themes.cfg
> +Art-Book-Not-Supported-Yet https://github.com/anthonycaccese/es-theme-art-book-3-2
```suggestion
Art-Book https://github.com/anthonycaccese/es-theme-art-book-3-2
```

2021-05-02 02:14 UTC, anthonycaccese commented on metadata/RG351V/themes.cfg
> +Art-Book-Not-Supported-Yet https://github.com/anthonycaccese/es-theme-art-book-3-2
Please remove "Not Supported" from this and Handheld Simple.  The themes work and display ok.

2021-05-02 02:14 UTC, anthonycaccese commented on metadata/RG351V/themes.cfg
> +Handheld-Simple-Not-Supported https://github.com/Rican7/es-theme-handheld-simple
```suggestion
Handheld-Simple https://github.com/Rican7/es-theme-handheld-simple

```

2021-05-02 02:14 UTC, anthonycaccese commented on metadata/RG351P/themes.cfg
> +Handheld-Simple-NOT-SUPPORTED https://github.com/Rican7/es-theme-handheld-simple
```suggestion
Handheld-Simple https://github.com/Rican7/es-theme-handheld-simple

```

2021-05-02 02:14 UTC, anthonycaccese commented on packages/351elec/config/distribution/modules/gamelist.xml
> +		<name>Start Remove ._ Files</name>
```suggestion
		<name>Run Remove ._ Files</name>
```

2021-05-02 02:14 UTC, anthonycaccese commented on packages/351elec/config/distribution/modules/gamelist.xml
> +		<name>Start Remove ._ Files</name>
Would suggest changing this to "Run" in place of "Start"

2021-05-02 02:14 UTC, anthonycaccese commented on packages/351elec/config/distribution/modules/gamelist.xml
> +		<desc>Clean up your not needed extensions</desc>
```suggestion
		<desc>Removes hidden ._ files created by the MacOS filesystem</desc>
```

2021-05-02 02:16 UTC, anthonycaccese commented
Overall this looks great, I made a few suggestions to update before final approval.   Great work, also the new image for clean files looks great.

2021-05-02 06:39 UTC, szalik-rg351 commented
> Overall this looks great, I made a few suggestions to update before final approval (you should be able to commit each just by pressing the commit suggestion button underneath each above). Great work, also the new image for clean files looks great.

thank you : ) applied

2021-05-02 09:30 UTC, Cebion approved these changes

2021-05-02 09:30 UTC, Cebion approved these changes

2021-05-02 09:31 UTC, Cebion approved these changes

2021-05-02 11:56 UTC, anthonycaccese approved these changes

2021-05-02 18:47 UTC, merged