It adds support for Sega Saturn (yabasanshiro core) to retrorun.
351ELEC/351ELEC pull request #405
Opened 2021-05-17 21:41 UTC by navy1978

2021-05-17 21:48 UTC, dhwz approved these changes

2021-05-18 06:47 UTC, dhwz requested changes
Can you please make the changes in runemu.sh a bit more generic like it is done with retroarch so we can call any libretro core just via retrorun.

2021-05-18 07:27 UTC, Cebion commented
Built clean fine last night, waiting for runemu changes

2021-05-18 20:14 UTC, navy1978 commented
> Can you please make the changes in runemu.sh a bit more generic like it is done with retroarch so we can call any libretro core just via retrorun.

done

2021-05-18 20:16 UTC, dhwz approved these changes

2021-05-19 10:51 UTC, anthonycaccese approved these changes

2021-05-19 10:54 UTC, merged