it adds show_fps optional parameter to retrorun.sh
351ELEC/351ELEC pull request #443
Opened 2021-05-29 15:42 UTC by navy1978

2021-05-29 17:57 UTC, XargonWan approved these changes

2021-05-30 09:58 UTC, dhwz requested changes
we need to test new libgo2 first

2021-05-30 13:20 UTC, navy1978 commented
> we need to test new libgo2 first

the two things are not related at all. (I'm testing the libgo2 at the moment)

2021-06-02 21:17 UTC, dhwz approved these changes

2021-06-02 21:18 UTC, merged