Cloud sync warning message
351ELEC/351ELEC pull request #545
Opened 2021-07-10 09:48 UTC by XargonWan

- added a warning message about the black screen before backup and restore

2021-07-11 12:21 UTC, dhwz requested changes
use changes as proposed by @pkegg

2021-07-12 02:17 UTC, pkegg approved these changes
I am going to approve - but please look into dhwz's comment around not using `-f` with textviewer - dhwz will likely not approve without changes for that. (I think if `-f` is adjusting font size, dhwz has a change to do it globally soon)

2021-07-12 03:51 UTC, pkegg commented
So - sorry for approving and then proposing more changes :).  But...

I was doing some rclone reading - I think the below will make the output better.  Basically, there is a `--log-level` and `--log-file` option so you can get rid of `-v` and no need to use `tee` (which was I think making rclone display a ton of output.)
```
rclone sync /storage/roms/ 351REMOTE:/351BACKUP/ --filter-from /roms/gamedata/rclone/cloud-sync-rules.conf -P --config /roms/gamedata/rclone/rclone.conf --log-level DEBUG --log-file /tmp/logs/cloud-sync.log 2>&1 > /dev/console
```

Also - I tried to test with Amazon s3 (technically minio).  In s3 - upper case letters are invalid (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html).  That means - `351BACKUP` is an invalid name for any s3 based solution (and as there are a lot of providers using the s3 interface, I think it makes sense to try and fix: https://rclone.org/s3/).  

So - I would strongly consider switching to `351REMOTE` => `351remote` and `351BACKUP` => `351backup`.  This change doesn't need to go into this PR, but it should probably be switched before release.

2021-07-15 14:53 UTC, pkegg approved these changes

2021-07-15 15:29 UTC, dhwz approved these changes

2021-07-15 15:32 UTC, merged